title: IBM WFM Microservices
author: steven-ponessa
email: ponessa@us.ibm.com
description: > # this means to ignore newlines until "baseurl:"
  This site holds the documentation for the microservieces.

# social links
twitter_username: ponessa # DO NOT include the @ character, or else the build will fail!
github_username:  steven-ponessa # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
